### ISSUE TITLE
Scroll position should be preserved when opening a ticket view and going back to the tickets list

### ISSUE THREAD

**Issue by mPastuszko** [packhelp/ua-matching-needs-ui#44]
As a user who is browsing the list of tickets, when I click/tap a ticket to see the details and then go back to the list of tickets, my scroll position is not preserved, so I need to scroll again to the ticket I was browsing, so that I can see the next tickets on the list.

Video: https://cln.sh/tlodiv

Reproduction steps:
1. Open a list of active tickets
2. Scroll to a ticket in the middle of the page
3. Click/tap the ticket to see its details
4. Click/tap back button

Expected result: My screen is scrolled to the position where I was browsing the list before (i.e. middle fo the screen), so that I can easily explore the tickets below the one I opened.

Actual result: I see the top of the list of tickets, so I need to manually scroll the list to the position where I was before.

Environment: Desktop and mobile (all browsers)

**Comment by SaraVieira** [comment]
Fixed in https://github.com/packhelp/ua-matching-needs-ui/pull/63
